#! /bin/sh

case "$1" in
    start)
        aesdchar_load
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        aesdchar_unload
        scull_unload
        module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
